# Generated by Django 5.0 on 2024-09-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
